# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 136ab7016f01b0ea6c60de33a4071cd6f8e9145d64498c0129bc15cd667673fc4f203ab0f59cd5e894eadf0775b77f30b265a5f7a15d6eb14f1b439208d4e40f

test:
  secret_key_base: b39c73a9e73e0d80a3fdba42682785b13397544660c07872fb01187796712a87d91e787718c4b592fda01ba9149888669114cbf05bd1ce95a288fd5952c22f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
